const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const STATUSES=new Set(["FAILED","DIPROSES","CAIR","REFUND","CANCEL"]);
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extra}});
const escText=v=>String(v??"").trim();
function normalizeStatus(v){const s=escText(v).toUpperCase();if(s.includes("REFUND"))return "REFUND";if(s.includes("PROCESS")||s.includes("PROSES"))return "DIPROSES";if(s.includes("SUCCESS")||s.includes("CAIR"))return "CAIR";if(s.includes("CANCEL"))return "CANCEL";return "FAILED";}
function parseAmount(v){let s=escText(v).replace(/[^\d,.-]/g,"");if(!s)return 0;if(s.includes(".")&&!s.includes(","))s=s.replace(/\./g,"");else if(s.includes(",")&&s.includes("."))s=s.replace(/\./g,"").replace(",",".");else if(s.includes(","))s=s.replace(/,/g,"");const n=Number(s);return Number.isFinite(n)?Math.round(n):0;}
function splitLine(line){if(line.includes("\t"))return line.split("\t").map(escText);const out=[];let cur="",quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){out.push(cur.trim());cur="";}else cur+=c;}out.push(cur.trim());return out;}
function headerMap(headers){const h=headers.map(x=>escText(x).toLowerCase().replace(/[\s_\-]+/g," ").trim());const find=(...names)=>{for(const n of names){const i=h.indexOf(n);if(i>=0)return i;}return -1;};return {no:find("no","no."),date:find("date","tanggal"),amount:find("amount","nominal"),bankCode:find("bank code","bankcode","kode bank"),bankName:find("bank name","bank","nama bank"),bankNo:find("bank no","bank number","no rekening","norek","account number","rekening"),accountName:find("account name","nama rekening","nama rek","nama"),ref:find("ref","reference"),vendorId:find("vendor id","vendorid","vendor"),status:find("status"),datetime:find("datetime","date time","tanggal waktu","waktu"),balanceRevert:find("balance revert","balancerevert")};}
function cell(row,i){return i>=0?escText(row[i]):"";}
function parseSixLineBlocks(text){const lines=text.split(/\r?\n/).map(escText).filter(Boolean);if(lines.length<6||lines.length%6!==0)return null;const blocks=[];for(let i=0;i<lines.length;i+=6){const [bankNo,accountName,ref,vendorId,sourceStatus,sourceDatetime]=lines.slice(i,i+6);blocks.push({source_no:"",tx_date:sourceDatetime.split(" ")[0]||sourceDatetime,amount:0,bank_code:"",bank_name:"",bank_no:bankNo,account_name:accountName,ref,vendor_id:vendorId,source_status:sourceStatus,source_datetime:sourceDatetime,balance_revert:""});}return blocks;}
function parseTabular(text){const lines=text.split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return null;const m=headerMap(splitLine(lines[0]));if(m.bankNo<0)return null;return lines.slice(1).map(line=>{const r=splitLine(line);return {source_no:cell(r,m.no),tx_date:cell(r,m.date),amount:parseAmount(cell(r,m.amount)),bank_code:cell(r,m.bankCode),bank_name:cell(r,m.bankName),bank_no:cell(r,m.bankNo),account_name:cell(r,m.accountName),ref:cell(r,m.ref),vendor_id:cell(r,m.vendorId),source_status:cell(r,m.status),source_datetime:cell(r,m.datetime),balance_revert:cell(r,m.balanceRevert)};});}
function cors(request){return {"access-control-allow-origin":request.headers.get("origin")||"*","access-control-allow-methods":"GET,POST,PATCH,OPTIONS","access-control-allow-headers":"content-type,x-staff-key","vary":"Origin"};}
function auth(request,env){if(!env.STAFF_API_KEY)return null;return request.headers.get("x-staff-key")===env.STAFF_API_KEY?null:new Response("Unauthorized",{status:401});}
async function api(request,env){const a=auth(request,env);if(a)return a;const c=cors(request);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:c});const u=new URL(request.url),p=u.pathname;
try{
 if(p==="/api/health"&&request.method==="GET")return json({ok:true,app:env.APP_NAME||"WD Failed Dashboard"},200,c);
 if(p==="/api/stats"&&request.method==="GET"){const r=await env.DB.prepare("SELECT process_status,COUNT(*) count,COALESCE(SUM(amount),0) total FROM withdrawals GROUP BY process_status").all();const s={FAILED:{count:0,total:0},DIPROSES:{count:0,total:0},CAIR:{count:0,total:0},REFUND:{count:0,total:0},CANCEL:{count:0,total:0}};for(const x of r.results||[])if(s[x.process_status])s[x.process_status]={count:Number(x.count),total:Number(x.total)};return json(s,200,c);}
 if(p==="/api/withdrawals"&&request.method==="GET"){const q=escText(u.searchParams.get("q")),status=escText(u.searchParams.get("status")).toUpperCase(),limit=Math.min(Math.max(Number(u.searchParams.get("limit")||200),1),300);let sql="SELECT * FROM withdrawals WHERE 1=1",b=[];if(q){sql+=" AND (bank_no LIKE ? OR account_name LIKE ? OR ref LIKE ? OR vendor_id LIKE ? OR bank_name LIKE ?)";const x=`%${q}%`;b.push(x,x,x,x,x);}if(STATUSES.has(status)){sql+=" AND process_status=?";b.push(status);}sql+=" ORDER BY datetime(created_at) DESC,id DESC LIMIT ?";b.push(limit);const r=await env.DB.prepare(sql).bind(...b).all();return json({rows:r.results||[]},200,c);}
 if(p==="/api/withdrawals/import"&&request.method==="POST"){
   const body=await request.json();const text=escText(body.text);if(!text)return json({error:"Data import kosong."},400,c);
   let records=parseTabular(text),format="tabel";if(!records){records=parseSixLineBlocks(text);format="6 baris";}
   if(!records||!records.length)return json({error:"Format tidak dikenali. Gunakan tabel dengan header atau 6 baris per transaksi: No Rekening, Nama, Ref, Vendor ID, Status, Datetime."},400,c);
   let inserted=0,updated=0,skipped=0;
   for(const d of records){if(!d.bank_no){skipped++;continue;}if(d.ref){const old=await env.DB.prepare("SELECT id FROM withdrawals WHERE ref=?").bind(d.ref).first();if(old){await env.DB.prepare("UPDATE withdrawals SET source_no=?,tx_date=?,amount=?,bank_code=?,bank_name=?,bank_no=?,account_name=?,vendor_id=?,source_status=?,source_datetime=?,balance_revert=?,updated_at=datetime('now') WHERE id=?").bind(d.source_no,d.tx_date,d.amount,d.bank_code,d.bank_name,d.bank_no,d.account_name,d.vendor_id,d.source_status,d.source_datetime,d.balance_revert,old.id).run();updated++;continue;}}
     await env.DB.prepare("INSERT INTO withdrawals (source_no,tx_date,amount,bank_code,bank_name,bank_no,account_name,ref,vendor_id,source_status,source_datetime,balance_revert,process_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(d.source_no,d.tx_date,d.amount,d.bank_code,d.bank_name,d.bank_no,d.account_name,d.ref,d.vendor_id,d.source_status,d.source_datetime,d.balance_revert,normalizeStatus(d.source_status)).run();inserted++;
   }
   return json({ok:true,inserted,updated,skipped,format},200,c);
 }
 const match=p.match(/^\/api\/withdrawals\/(\d+)$/);if(match&&request.method==="PATCH"){const id=Number(match[1]),body=await request.json(),newStatus=escText(body.process_status).toUpperCase(),staff=escText(body.processed_by).slice(0,100),note=escText(body.note).slice(0,1000);if(!STATUSES.has(newStatus))return json({error:"Status tidak valid."},400,c);if(!staff)return json({error:"Nama staff wajib diisi."},400,c);const old=await env.DB.prepare("SELECT * FROM withdrawals WHERE id=?").bind(id).first();if(!old)return json({error:"Transaksi tidak ditemukan."},404,c);await env.DB.prepare("UPDATE withdrawals SET process_status=?,processed_by=?,processed_at=datetime('now'),note=?,updated_at=datetime('now') WHERE id=?").bind(newStatus,staff,note,id).run();await env.DB.prepare("INSERT INTO audit_logs (withdrawal_id,action,old_status,new_status,staff,note) VALUES (?, 'STATUS_CHANGE', ?, ?, ?, ?)").bind(id,old.process_status,newStatus,staff,note).run();return json({ok:true},200,c);}
 const audit=p.match(/^\/api\/withdrawals\/(\d+)\/audit$/);if(audit&&request.method==="GET"){const r=await env.DB.prepare("SELECT * FROM audit_logs WHERE withdrawal_id=? ORDER BY id DESC").bind(Number(audit[1])).all();return json({rows:r.results||[]},200,c);}
 return json({error:"Not found"},404,c);
}catch(e){return json({error:e?.message||"Server error"},500,c);}}
export default {async fetch(request,env){const u=new URL(request.url);if(u.pathname.startsWith("/api/"))return api(request,env);return env.ASSETS.fetch(request);}};
